#!/usr/bin/env bash
# First-time deploy automation for bluewave-worker.
#
# Idempotent: safe to re-run. Generates .env (Fernet key + bcrypt operator
# hash) if missing, builds the image, brings up the container, and waits
# for /healthz to respond. After this script finishes, the operator opens
# the web UI to fill in BlueWeb / MySQL / schedule.
#
# Usage:
#   ./deploy.sh                # interactive (prompts for password)
#   FORCE_REGEN=1 ./deploy.sh  # delete and regenerate .env
#
# Requirements:
#   - docker (Engine 20.10+) with the `compose` v2 subcommand
#   - bash 4+, curl

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
IMAGE_TAG="bluewave-worker:dev"
SERVICE_NAME="bluewave-worker"
WORKER_URL="${WORKER_URL:-http://localhost:8080}"
HEALTHZ_TIMEOUT_S="${HEALTHZ_TIMEOUT_S:-60}"

# ---------- pretty output --------------------------------------------------

c_info() { printf '\033[36m[deploy]\033[0m %s\n' "$*"; }
c_ok()   { printf '\033[32m[deploy]\033[0m %s\n' "$*"; }
c_warn() { printf '\033[33m[deploy]\033[0m %s\n' "$*" >&2; }
c_err()  { printf '\033[31m[deploy]\033[0m %s\n' "$*" >&2; }
fatal()  { c_err "$*"; exit 1; }

# ---------- prerequisite checks --------------------------------------------

c_info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fatal "docker not found in PATH"
docker compose version >/dev/null 2>&1 \
    || fatal "'docker compose' (v2) not found — install Docker Compose v2"
command -v curl >/dev/null 2>&1 || fatal "curl not found in PATH"

if ! docker info >/dev/null 2>&1; then
    fatal "docker daemon not reachable (is the engine running?)"
fi

c_ok "docker $(docker --version | awk '{print $3}' | sed 's/,//')"

# ---------- regen guard ----------------------------------------------------

if [[ "${FORCE_REGEN:-0}" == "1" && -f "$ENV_FILE" ]]; then
    c_warn "FORCE_REGEN=1 — removing existing $ENV_FILE"
    rm -f "$ENV_FILE"
fi

# ---------- build ----------------------------------------------------------
# Build before generating secrets so we can use the built image to run the
# Python helpers (avoids pulling another base image).

c_info "Building image $IMAGE_TAG..."
docker compose build "$SERVICE_NAME" >/dev/null
c_ok "build complete"

# ---------- generate .env --------------------------------------------------

if [[ -f "$ENV_FILE" ]]; then
    c_info "$ENV_FILE already exists; skipping generation"
    c_info "  (run 'FORCE_REGEN=1 ./deploy.sh' to wipe and regenerate)"
else
    c_info "Generating $ENV_FILE..."

    c_info "  - generating CONFIG_ENC_KEYS via python -m bluewave.keygen"
    config_enc_keys=$(docker run --rm "$IMAGE_TAG" python -m bluewave.keygen)
    [[ -n "$config_enc_keys" ]] || fatal "keygen produced empty output"

    if [[ -n "${WEB_USER:-}" ]]; then
        web_user="$WEB_USER"
        c_info "  - using WEB_USER from environment: $web_user"
    else
        read -rp "Operator web UI username [admin]: " web_user
        web_user="${web_user:-admin}"
    fi

    if [[ -n "${WEB_PASS:-}" ]]; then
        web_pass="$WEB_PASS"
        c_info "  - using WEB_PASS from environment"
    else
        # -s suppresses echo. Two prompts for confirmation.
        read -rs -p "Operator web UI password (min 8 chars): " web_pass
        echo
        read -rs -p "Confirm password:                        " web_pass2
        echo
        [[ "$web_pass" == "$web_pass2" ]] || fatal "passwords do not match"
    fi
    [[ ${#web_pass} -ge 8 ]] || fatal "password must be at least 8 characters"

    c_info "  - hashing password via python -m bluewave.hashpw --stdin"
    web_pass_hash=$(printf '%s\n' "$web_pass" \
        | docker run --rm -i "$IMAGE_TAG" python -m bluewave.hashpw --stdin)
    [[ -n "$web_pass_hash" ]] || fatal "hashpw produced empty output"
    unset web_pass web_pass2

    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Keep this file out of git. Re-run deploy.sh with FORCE_REGEN=1 to rotate.

CONFIG_ENC_KEYS=$config_enc_keys
WEB_USER=$web_user
WEB_PASS_HASH=$web_pass_hash
WEB_ALLOW_HTTP=1
EOF
    chmod 600 "$ENV_FILE"
    c_ok "$ENV_FILE created (mode 600)"
fi

# ---------- bring up -------------------------------------------------------

c_info "Starting container..."
docker compose up -d
c_ok "container started"

# ---------- wait for /healthz ----------------------------------------------

c_info "Waiting for $WORKER_URL/healthz (timeout ${HEALTHZ_TIMEOUT_S}s)..."
deadline=$(( $(date +%s) + HEALTHZ_TIMEOUT_S ))
code="000"
while [[ $(date +%s) -lt $deadline ]]; do
    code=$(curl -sS -o /tmp/bluewave_healthz.$$ -w '%{http_code}' "$WORKER_URL/healthz" || echo "000")
    if [[ "$code" == "200" || "$code" == "503" ]]; then
        break
    fi
    sleep 2
done

if [[ "$code" != "200" && "$code" != "503" ]]; then
    rm -f /tmp/bluewave_healthz.$$
    c_err "container did not respond on /healthz within ${HEALTHZ_TIMEOUT_S}s (last code: $code)"
    c_err "tail of 'docker compose logs':"
    docker compose logs --tail=40 "$SERVICE_NAME" >&2 || true
    exit 1
fi

status=$(python3 -c '
import json, sys
try:
    print(json.load(open("/tmp/bluewave_healthz.'"$$"'")).get("status","?"))
except Exception:
    print("?")
' 2>/dev/null || echo "?")
rm -f /tmp/bluewave_healthz.$$

c_ok "/healthz responded (status=$status, HTTP $code)"

# ---------- next steps -----------------------------------------------------

echo
case "$status" in
    unconfigured)
        web_user_show=$(grep '^WEB_USER=' "$ENV_FILE" | cut -d= -f2-)
        c_info "Container is up and waiting for configuration."
        echo
        echo "  Next steps:"
        echo "    1. Open  $WORKER_URL/config"
        echo "    2. Log in as  $web_user_show  (the password you just entered)"
        echo "    3. Fill in:"
        echo "         - Site label (e.g. 'Easy Foods Inc.')"
        echo "         - BlueWeb URL / username / password"
        echo "         - Operator timezone (IANA, e.g. America/New_York)"
        echo "         - MySQL host / port / database / user / password"
        echo "         - Schedule (HH:MM in operator timezone)"
        echo "    4. Click 'Test BlueWeb' and 'Test MySQL' to validate"
        echo "    5. Save — the daily cron registers and boot-time catch-up runs"
        ;;
    ok)
        c_ok "Container is configured and healthy. Dashboard: $WORKER_URL/"
        ;;
    degraded)
        c_warn "/healthz status=degraded — check 'docker compose logs $SERVICE_NAME'"
        ;;
    *)
        c_warn "unexpected /healthz status: $status"
        ;;
esac
echo
